name: flutter_flash_chat_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_progress_hud: ^2.0.2
  firebase_core_desktop: ^1.0.2
  firebase_auth_desktop: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  firebase_for_all: ^0.1.1

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
