// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBn31pTgPAukqsfdRaziL3PY0CsJdWgtc',
    appId: '1:252045518561:web:6d772c4006999f29ddf9a0',
    messagingSenderId: '252045518561',
    projectId: 'flash-chat-b7e5f',
    authDomain: 'flash-chat-b7e5f.firebaseapp.com',
    storageBucket: 'flash-chat-b7e5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfBwVnrzJ0VrGHqPoTqr8IKcTSEP4hEE',
    appId: '1:252045518561:android:45b50fe18bf8b8b8ddf9a0',
    messagingSenderId: '252045518561',
    projectId: 'flash-chat-b7e5f',
    storageBucket: 'flash-chat-b7e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk4_yzLnxjI2SE5GJdvgExp6DiNGkNyg4',
    appId: '1:252045518561:ios:c8eeaf782e09a361ddf9a0',
    messagingSenderId: '252045518561',
    projectId: 'flash-chat-b7e5f',
    storageBucket: 'flash-chat-b7e5f.appspot.com',
    iosClientId: '252045518561-chmf2s4qmpr1ag5q6v9ttt4qsntc7f8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlashChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk4_yzLnxjI2SE5GJdvgExp6DiNGkNyg4',
    appId: '1:252045518561:ios:c8eeaf782e09a361ddf9a0',
    messagingSenderId: '252045518561',
    projectId: 'flash-chat-b7e5f',
    storageBucket: 'flash-chat-b7e5f.appspot.com',
    iosClientId: '252045518561-chmf2s4qmpr1ag5q6v9ttt4qsntc7f8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlashChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBn31pTgPAukqsfdRaziL3PY0CsJdWgtc',
    appId: '1:252045518561:web:889d6ba923a2582dddf9a0',
    messagingSenderId: '252045518561',
    projectId: 'flash-chat-b7e5f',
    authDomain: 'flash-chat-b7e5f.firebaseapp.com',
    storageBucket: 'flash-chat-b7e5f.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBBn31pTgPAukqsfdRaziL3PY0CsJdWgtc',
    appId: '1:252045518561:web:1834d23a3c087254ddf9a0',
    messagingSenderId: '252045518561',
    projectId: 'flash-chat-b7e5f',
    authDomain: 'flash-chat-b7e5f.firebaseapp.com',
    storageBucket: 'flash-chat-b7e5f.appspot.com',
  );
}
